// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewStudent struct {
	Name   string  `json:"name"`
	Grades *string `json:"grades"`
}

type Student struct {
	ID     string  `json:"id"`
	Name   string  `json:"name"`
	Grades *string `json:"grades"`
}

func (Student) IsEntity() {}
