// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Assignment struct {
	StudentID string  `json:"studentId"`
	Title     *string `json:"title"`
}

func (Assignment) IsEntity() {}

type NewAssignment struct {
	Title     *string `json:"title"`
	StudentID string  `json:"studentId"`
}

type Student struct {
	ID         string      `json:"id"`
	Assignment *Assignment `json:"assignment"`
}

func (Student) IsEntity() {}
